name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build VSIX
      shell: bash
      run: |
        npm install
        npm install -g vsce
        vsce package -o brogue-rpg-tools.vsix
    - uses: actions/upload-artifact@v4
      with:
        name: brogue-rpg-tools.vsix
        path: brogue-rpg-tools.vsix
    - name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
        extensionFile: brogue-rpg-tools.vsix
      if: startsWith(github.ref, 'refs/tags/')
